[package]
name = 'candidate_staking2'
version = '0.0.3'

[addresses]
CandidateStaking = "0x9db1d65a321e4a86f8098cb04e76fce098890b84211fa06d65f24dc644bf0fec"
CoreResources = "0xA550C18"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev="devnet"}
